# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 52546e261a32790647228c480ab07bf3ec4f9b88e736485c67fb821cfaab945161880d94d4f23349d0c71322de7128728b71dfa8feb2d25ea1469193cf00b9cb

test:
  secret_key_base: f6bfdddf3f8113a3012c6b8f9372cf7d8ec2f44c8f38daec44c14ac786ff02ff7ab0c5db67feca6cbfdfe00ecdacb6331cca6e4a62c016efb002a24ea76382b0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
